# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:

# image: python:3.9
# image: continuumio/miniconda3:latest
#   before_script:
#     - apt-get install -y git curl python-pip python-dev python3-dev build-essential doxygen miniconda
#     - apt-get update -qy

#   script:
#     - python -v
#     - conda -v

    # - apt-get install -y curl
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

py39:
  image: continuumio/miniconda3:latest
  before_script:
    - conda env create -n py39 -f ./environment.yml
    - source activate py39
    - python -v
    # - python -m pip install --upgrade pip
    - git config --global user.email "nlpia2+gitlabcicd@totalgood.com"
    - git config --global user.name "_NLP in Action 2nd Ed_ Contributors"
    - python -m pip install -e .
  script:
    - pytest

pages:
  image: python:3.9
  stage: deploy
  script:
    # m2r+mistune versions [required by Sphinx](https://github.com/CrossNox/m2r2/issues/40)
    - pip install sphinx recommonmark m2r==0.2.1 mistune==0.8.4
    - cd docs
    - make html
    - cp -r _build/html ../public
  artifacts:
    paths:
      - public/
  only:
    - main

