# .gitlab-ci.yml keyword reference
# https://docs.gitlab.com/ee/ci/yaml/

# Official Python 3.9 language image.
test_py39:
  image: python:3.9
  before_script:
    - apt-get install python3-*
    - pip install --upgrade pytest-cov wheel pip virtualenv build twine
    - pip install -e .
    - python -m spacy download en_core_web_sm
    - python -m spacy download en_core_web_md
  script:
    - pytest --verbose
#    - pytest --doctest-modules --doctest-glob='*.adoc' --doctest-glob='*.rst' --doctest-glob='*.py' --verbose

