[project]
name = "nlpia2"
version = "0.2.1"
description = "NLP utilities and examples for _Natural Language Processing in Action, 2nd Ed_, by Hobson Lane and Maria Dyshel"
readme = "README.md"
authors = [
    {name = "Hobson Lane", email = "gitlab@totalgood.com"},
    {name = "Maria Dyshel", email = "maria@tangibleai.com"},
    {name = "Ethan Cavill", email = "ethancavill@gmail.com"},
    {name = "Geoffrey Marshal"},
    {name = "Sylvia Lee"},   
    {name = "Greg Thompson", email = "greg@tangibleai.com"},   
    {name = "Winnie Yeung @dcvionwinnie"},
    {name = "Leo Hepis", email = "leo@leohepis.com"},
    {name = "Mohammed Dala Ali", email = "mms.dala@gmail.com"},
    {name = "Alex Rosengarten @alxrsngrtn"},
    {name = "Jose Robins @jorobins"},
]
homepage = "https://nlpia.org"
repository = "https://gitlab.com/tangibleai/nlpia2"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12",
    "bidict>=0.22.1",
    "boto3>=1.34.6",
    "configargparse>=1.7",
    "cython>=3.0",
    "dateparser>=1.1.8",
    "edit-distance>=1.0.6",
    "einops>=0.6.1",
    "fuzzywuzzy",
    "fastapi>=0.105.0",
    "gradio",  # >=3.0,<4.0",
    "h5py>=3.9.0",
    "huggingface-hub>=0.16.4",
    "html2text>=2020.1.16",
    "ipython",
    "joblib>=1.3.2,<1.4",
    "jsonlines>=3.1.0",
    "jupyter",
    "jupyter-console",
    "jupyterlab>=4.0.10",
    "jupyter-console>=6.6.3",
    "langchain>=0.0.265",
    "lxml>=4.9.3",
    "matplotlib",
    "matplotlib-inline",
    "meilisearch",
    "mistune>=3.0.1",
    "nessvec>=0.2.0",
    "nlpia2-wikipedia>=1.5.14",
    "nltk>=3.8.1",
    "numpy>=1.26.2,<1.27",
    "openai>=0.27.8",
    "pandas>=2.2.0,<2.3",  # pandas-gbq>=*"  # pandas oauthlib requests google-auth requests-oathlib proto-plus urllib3 pyarrow pytz python-dateutil,
    "pytest-coverage",
    "pip",
    "plotly",
    "poetry",
    "pronouncing>=0.2.0",
    "psutil>=5.9.5", # ,<5.10",
    "python-dotenv>=1.0.0",
    "pyvis>=0.3.2",
    "scikit-learn",     # scipy==1.11.4,joblib,numpy,threadpoolctl,
    "seaborn>=0.13.0",  # pandas fonttools matplotlib numpy contourpy cycler pillow packaging python-dateutil pytz tzdata six,
    "sentence_transformers>=2.2.2",
    "spacy", # >=3.7.2,<3.8",
    "sphinx>=7.1.2",
    "streamlit>=1.25.0",
    "textacy>=0.13.0",
    "toml>=0.10.2",
    "tox>=4.8.0",
    "tqdm>=4.66.1",
    "unidecode>=1.3.6",
    "xmltodict>=0.13.0",
]

documentation = "https://nlpia.org"
keywords = ["NLP", "Natural Language Processing", "Virtual Assistant", 
    "chatbot", "LLM", "vector-search", "Text Processing", "Machine Learning",
    "Text Mining", "Deep Learning", "numpy", "search", "semantic search", "RAG", 
    "personal assistant", "command line", "text generation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Linguistic",
    "Topic :: Text Processing", "Topic :: Communications",
    "Topic :: Communications :: Chat", "Intended Audience :: Education",
    ]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
